### ISSUE TITLE
"Build automatically" preference keeps getting turned off

### ISSUE THREAD

**Issue by akurtakov** [mickaelistria/eclipse.jdt.ls.client#20]
Since I have jdt.ls.client build automatically keeps getting turned off. Just restart and it's turned off again.

**Comment by akurtakov** [comment]
So this one comes from https://github.com/mickaelistria/eclipse.jdt.ls/blob/c66bab131df45f5e7a861d9c610952d17eecedfb/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java#L171 and it looks like there would either be a some preference to pass to the LS in order to not disable it or there would have to be some "if (!eclipse)" kind of guard.

**Comment by akurtakov** [comment]
I'm trying with :
```java
if (!JavaLanguageServerPlugin.runInEclipseWorkbench) {
			try {
				Platform.getBundle(ResourcesPlugin.PI_RESOURCES).start(Bundle.START_TRANSIENT);
				IWorkspace workspace = ResourcesPlugin.getWorkspace();
				IWorkspaceDescription description = workspace.getDescription();
				description.setAutoBuilding(false);
				workspace.setDescription(description);
			} catch (BundleException e) {
				logException(e.getMessage(), e);
			}
		}
```

**Comment by akurtakov** [comment]
The submodule of jdt.ls is nice as a bandaid to have smth working but unfortunately I haven't figured out how to contribute to my jdt.ls fork from https://github.com/eclipse/eclipse.jdt.ls and contribute to @mickaelistria fork a PR. 
FYI, @rgrunber .

**Comment by rgrunber** [comment]
Doing a quick look, autobuild is set on `didChangeConfiguration`, which should get called as part of initialization. It doesn't look like we set the auto-build on initialization, which is weird to me, but maybe it works because most clients call `didChangeConfiguration` anyways. Maybe the spec says something about that. Should a client make sure to call that or is it not guaranteed ? The other possibility, is maybe one of the other places that set the auto-build to false is being triggered and it's just a matter of figuring out why.

**Comment by mickaelistria** [comment]
Spec says "A notification sent from the client to the server to signal the change of configuration settings."; here there are no change of configuration settings, it's still the default changes from initializationOptions that are to be used.
So I think the server shouldn't expect that the clients will necessarily send this notification, ie JDT-LS should probably just set it upon initialization.

Still I don't get fully why those lines are necessary here. If they happen to be necessary, are they always necessary or just in case of JDT-LS run via the application? And if it's the later, is the application running on a clean workspace everytime? If so we may just check that the workspace is empty before changing this configuration?

**Comment by rgrunber** [comment]
Found https://github.com/eclipse/eclipse.jdt.ls/pull/2252 . Looks like we do it for performance. 

@snjeza, @gayanper, If some clients (eg. jdt.ls.client) want the autobuild to trigger as soon as it's safe to do so (not concerned with startup performance), could we just add some kind of : `if (!preferenceManager.getPreferences().deferAutoBuild()) { setAutoBuilding(true); }` at https://github.com/eclipse/eclipse.jdt.ls/blob/f704b7a0f27bc7e693ff7fff5aa678f945c5bf5f/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java#L564-L565 ?

**Comment by mickaelistria** [comment]
Fixed with #21

**Comment by akurtakov** [comment]
Happens again with   Java edition support using JDT Language Server Client	0.1.0.202302231543	.

**Comment by mickaelistria** [comment]
It doesn't get disabled on startup as far as I see, but it can be disabled "randomly" some times. I suspect there is another place in JDT-LS where auto-build gets disabled for some operation, and not restored to previous value after.

**Comment by mickaelistria** [comment]
The reason why my patch doesn't always work is that in some cases, on a restart, the JDT-LS plugin will start before the client one, so the client doesn't know about the value of auto-build before JDT-LS starts. https://github.com/eclipse/eclipse.jdt.ls/pull/2503 or similar would be a better fix and would also make things clearer on the LS-side (and progressively allow things like multiple clients in the same JDT-LS process, although hopefully it will never be necessary)

**Comment by mickaelistria** [comment]
This should now be fixed with https://github.com/eclipse/eclipse.jdt.ls/pull/2503
