### ISSUE TITLE
New line in Javadoc comment doesn't add the ` *` prefix

### ISSUE THREAD

**Issue by mickaelistria** [mickaelistria/eclipse.jdt.ls.client#30]
From
```java
/**
  * Blah blah
  */
```
Press Enter at the end of `Blah blah` line, a newline is created (good) but it misses the ` *` prefix that can be inferred from the context.

**Comment by mickaelistria** [comment]
We're currently using the language-configuration from VSCode: https://github.com/microsoft/vscode/blob/main/extensions/java/language-configuration.json which doesn't include the necessary onEnterRules to enable it, unlike typescript language configuration for example.
However, this feature works in VSCode....
@rgrunber is it something VSCode Java brings?

**Comment by rgrunber** [comment]
See https://code.visualstudio.com/api/language-extensions/language-configuration-guide#on-enter-rules & https://github.com/redhat-developer/vscode-java/blob/e3778ebe3063c8ee8e6b14908b542ef216cd78cb/src/extension.ts#L551-L589

**Comment by mickaelistria** [comment]
OK, I verified and this can be provided directly in the language-configuration. I'll fix it that way for the Eclipse integration and will submit a PR to VSCode as well; then you'll be able to remove those 30 lines from vscode-java.

**Comment by mickaelistria** [comment]
I submitted https://github.com/microsoft/vscode/pull/176800 for VSCode and https://github.com/rgrunber/eclipse.jdt.ls.client/pull/31 here
